// * Admin action types
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_IN_WARNING = "SIGN_IN_WARNING";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const LOG_OUT = "LOG_OUT";

// * User action types
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";

export const USER_SIGN_IN_ERROR = "USER_SIGN_IN_ERROR";
export const USER_SIGN_IN_WARNING = "USER_SIGN_IN_WARNING";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";

export const USER_LOG_OUT = "USER_LOG_OUT";

export const GET_ALL_SAREES = "GET_ALL_SAREES";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const GET_FAVORITE_ITEMS = "GET_FAVORITE_ITEMS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";

export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_FAVORITE_ITEM = "DELETE_FAVORITE_ITEM";

export const ORDER_SUCCESS = "ORDER_SUCCESS";

export const GET_ORDERS = "GET_ORDERS";

export const RESET_LINK_SENT_SUCCESS = "RESET_LINK_SENT_SUCCESS";
export const RESET_LINK_SENT_ERROR = "RESET_LINK_SENT_ERROR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

